### ISSUE TITLE
Uncaught TypeError: cannot read properties of null (reading addEventListener)

### ISSUE THREAD

**Issue by aviv82** [lab-antwerp-1/home#197]
# please help
>I am trying to apply conditionals in a webpage for practice, but having trouble with `eventListener`

## my html

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="js/index.js"></script>
    <link rel="stylesheet" href="style/style.css" />
    <title>Insect Classifier</title>
  </head>
  <body>
    <h1>Insect Classifier</h1>
    <p>
      Hello friend, and welcome. <br />
      If you have an insect. this webpage will help you classify it <br />
      all you need to do is answer a simple questions
      <button class="start">Let's Begin</button>
    </p>
    <div class="first">
      <p>ok! how many legs does your arthropod has?</p>
      <input type="text" />
      <button>Reply</button>
    </div>
  </body>
</html>
```

## my js

```javascript
"use strict";

const startBtn = document.querySelector(".start");
const firstQuestion = document.querySelector(".first");

startBtn.addEventListener("click", () => {
  if (firstQuestion.style.display === "none") {
    firstQuestion.style.display = "block";
  } else {
    firstQuestion.style.display = "none";
  }
});
```
## Best Understanding

- i am trying to set up a function for when the first button is clicked by the user
the div with the first question and button appear.
- instead i am getting an error message in my console which says:
>Uncaught TypeError: cannot read properties of null (reading addEventListener)

## Best Efforts

- i tried doing this with an `onclick= function()` in html  on the button and it worked, 
but i thought using the new es6 `() =>` function is better..? 
- read some troubleshoots for the above error message and it says the DOM is loading in the worng order and thats why my classes are not found by the `querySelector`. 
- i tried using ids instead of classes but still no luck
- tried adding `window.addEventListener('load',Loaded,false);` on top of my js but it did nothing

## Helpful Links

- followed these tutorials;

[one](https://www.youtube.com/watch?v=KB6Yg5hNrqc&t=570s)
[two](https://www.youtube.com/watch?v=6x7twDuMWP0)

- and this troubleshoot page: 

[ts](https://stackoverflow.com/questions/14207922/javascript-error-null-is-not-an-object)

> thanks for your help! 😀

**Comment by bermarte** [comment]
I think you need to move the .js script at the end of your .html file (before `</body>`)

**Comment by gelilaa** [comment]
Wow @aviv82 its good to see that you are exploring new ways to learn JavaScript. DOM access and manipulation  will be covered in the separation of concern module deeply. 

For now here is my suggestion:
- it is probably because the script is executed before the page loads. By placing the script at the bottom of the page might solve the problem 
- Try to use ID instead of class and create a handler with [Document.getElementById()](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) 

I’m sure the coaches will have other suggestions as well … good luck 😉

**Comment by aviv82** [comment]
> I think you need to move the .js script at the end of your .html file (before `</body>`), you are trying to access the DOM before it is defined.

Thank you! it worked1

**Comment by aviv82** [comment]
> Wow @aviv82 its good to see that you are exploring new ways to learn JavaScript. DOM access and manipulation will be covered in the separation of concern module deeply.
> 
> For now here is my suggestion:
> 
> * it is probably because the script is executed before the page loads. By placing the script at the bottom of the page like @bermarte suggested might solve the problem
> * Try to use ID instead of class and create a handler with [Document.getElementById()](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)
> 
> I’m sure the coaches will have other suggestions as well … good luck 😉

Thank you! moving the script down did the trick. 💫

**Comment by aviv82** [comment]
actually i discovered something neat. inside the `<script>` bracket in the html document if we write `defer` js will only load after the html has all loaded. like so:

```html
    <script defer src="js/index.js"></script>
```
