### ISSUE TITLE
aviv: workflows 1 + 2

### ISSUE THREAD

**Issue by aviv82** [lab-antwerp-1/home#31]
# thursday check-in

## Learning Objectives

- 🥚 **Git Remote/Local Connection**: You can:
- [x] create a local git repository
- [x] commit changes
- [x]  connect a remote repository
- [x]  push changes to the remote.
- 🥚 **Linting**: what is it? why does it matter? 
- [x] can write CSS & Markdown that passes a linting check
- 🥚 **Git Branching Workflow**: You can:
- [x] manage your work locally using branches
- [x] pull remote changes
- [x]  create a new branch 
- [x]  push the branch to the remote repository 
- [x]  open a PR with passing Continuous Integration checks 
- [x]  merge changes to `main`/`master`.
- 🥚 **Command Line Interface \(CLI\)**: You can: 
- [x] navigate a directory
- [x]  manage folders/files
- [ ]  make small changes in a file using nano/vim, and much more \(list coming soon\).
- 🥚 **NPM**: You can: 
- [x] install npm dependencies
- [x]  use npm scripts \(`dev`, `lint` and `format`\)
- 🥚 **Browser + DevTools**: You can:
- [x] open a local HTML/CSS project in your browser 
- [x]  inspect the elements 
- [ ] emulate different devices
- [ ]  inspect the source
- 🥚 **File Extensions**: You can:
- [ ] identify all of the languages covered at HYF and give the correct file extension. \(You don't need to know the languages, just recognize them!\)
- 🥚 **VSCode**: You can complete these workflows in VScode, and can use keyboard shortcuts when possible:
  - [x] Opening a repository in a new window
  - [x] Opening the repository in VSCode terminal
  - [x] Adding a new file
  - [x] Adding a new folder
  - [x] Deleting a file
  - [x] Deleting a folder
  - [x] Previewing a Markdown File
  - [x] Opening an HTML file with the _LiveServer_ extension
  - [x] Viewing the repository's git history with _Git Graph_ extension
- 🐣 **Touch Typing**: You can:
- [ ] write a README without looking at your keyboard to find any letters, numbers or special characters. \(slowly is ok!\)
- 🐣 **User Stories**: Given pictures of a website, you can:
- [x] describe the page with user stories: As a _type of user_ I can _do something_ so that _something good happens_.
- 🐣 **Planning and Collaborating**: You can comfortably complete these steps of the _Planning and Collaborating_ process described in the Student Guidebook:
  - [x] Repository Setup
  - [x] Project Definition
  - [x] Communication Plan
  - [x] Backlog
  - [x] Wireframe
- 🐣 **Development Strategies**: You can: 
- [x] work as a group to follow the steps in a development strategy
- [x]  reconstruct a web page when the code is provided.
- 🐣 **Atomic Commits & Feature Branches**: You can: 
- [x] organize your development process using small single-purpose commits on feature branches. You will learn to develop each of these features on a separate branch and to merge it to `main`/`master` on GitHub when the feature is complete.
- 🐣 **GitHub**: You can: 
- [x] create new repositories
- [x]  turn on GitHub Pages
- [x]  connect the repository to your local computer
- [x]  push/pull different branches 
- [x] pass Continuous Integration checks for code _linting_ and _validation_.
- 🐥 **GitHub Collaboration**: You can:
- [x]  collaborate in a single repository and contribute a markdown file. 
- [x] create a new branch
- [x]  create and edit a file on that branch 
- [x] send a pull request 
- [x] address any requested changes
- [x]  review +merge a classmate's pull request. \(this can all be done from the GitHub UI\)
- 🐥 **Code Review**: You can:
- [ ] use a code review checklist in a Pull Request to check a classmates code before merging.

**Comment by gelilaa** [comment]
@aviv82 could you move your check-in to a comment in this issue? The issue will be easier to understand if you have only your study plan in the main description and your check-ins + our discussions in the comments.

Let us know what you have covered in your study plan from the list of [suggested-study](https://home.hackyourfuture.be/curriculum/workflows/suggested-study)

for reference check out [this ](https://github.com/HackYourFutureBelgium/class-15/issues/321)issue

**Comment by aviv82** [comment]
> @aviv82 could you move your check-in to a comment in this issue? The issue will be easier to understand if you have only your study plan in the main description and your check-ins + our discussions in the comments.
> 
> Let us know what you have covered in your study plan from the list of [suggested-study](https://home.hackyourfuture.be/curriculum/workflows/suggested-study)
> 
> for reference check out [this ](https://github.com/HackYourFutureBelgium/class-15/issues/321)issue

sure thing. thanks for the input!

**Comment by colevandersWands** [comment]
> then with the spell check i add the new words to the dictionary file, but sometimes the spell-check still picks the same words afterwards.

Don't worry so much about the spell check, it's more brittle.  The GitHub checks don't use the spellcheck, it's just a helpful tool for you when editing locally.

**Comment by aviv82** [comment]
>Do you fix the problems by editing the file?

not directly. i guess that's what i'm doing wrong... i just clicked on the little "lightbulbs" next to the errors in the "problems" tab and chose "fix".
