### ISSUE TITLE
Darin: Workflows, 1

### ISSUE THREAD

**Issue by Darin-Hamouda** [lab-antwerp-1/home#37]
<!-- you will create ONE check-in issue per module
# Suggested Study:

## Command Line Interface (CLI)
[] relative vs. absolute paths
[] The Coding Train
[] Jesse Showalter
[] CLI games:
   [] bashcrawl - clone & play
   [] Terminus - online
   [] iTerm - online
[] A huge cheat sheet

## Visual Studio Code (VSCode):
[] academind VSC tutorial
[] shortcuts cheatsheet
[] The Coding Train
VSC Intro from VSC
[] tutorial step-through
[] get started
[] Tips for HTML/CSS/JS
Are you using Windows?
[] Windows Subsystem for Linux
[] WSL with VSCode
[] nvm command not found

## Code Quality
[] formatting (all file types with prettier)
[] linting
   [] CSS
   [] markdown
[] validating HTML
[] spelling checks (will do once by automation, then by hand. automated spell checks are a little annoying)

## READMEs
[] makeareadme.com
[] bulldogjob
[] meakaakka
[] awesome-README-templates

## Git and GitHub

Git and GitHub for Poets
Learn to visualize what happens inside of Git with:
learngitbranching + a Video Guide
ohmygit - a git game
HYF/study
lab.github.com/githubtraining
first day on github
first week on github
prepare to use github
Getting Started with GitHub
Creating a GitHub Repository
Creating a local repo and push
and much more at hackyourfuture.github.io/study
lab.github.com:
First Day on GitHub
First Week on GitHub
The Net Ninja
git-it
Understand how to use Atomic Commits

## Collaborating on GitHub
Adding collaborators to a repository
about code reviews
requesting a code review
Git Workflow for 2
Pull Requests
Git & GitHub for Poets
The Net Ninja: 11
linking PRs to Issues: reference 1, reference 2
closing Issues using keywords

## GitHub Actions
For now you can think of Continuous Integration is a fancy way to say "automatically check your code before you merge". Your project repositories will all have CI scripts to help maintain a quality and consistent code base.
hint: remember to enable GitHub Actions in your repository!

## DevTools and the DOM
How to inspect an element
inspecting-the-dom
Modify the DOM. (does the source change?)

## Class Recordings
HYF modules are often updated, recordings from past classes may not match this gitbook
When sending a PR's with recording links please ...
Indicate which class you were teaching
Which week it was (if the module is more than 1 week)
a helpful title or description
How to inspect an element
inspecting-the-dom
Modify the DOM. (does the source change?)

**Comment by bermarte** [comment]
Hi @Darin-Hamouda You should leave your issue open. Linting is a code analysis tool used to find programming errors, bugs, and style errors. https://www.youtube.com/watch?v=HDQXWr5TOnI

**Comment by Darin-Hamouda** [comment]
@bermarte 
I have another issue #28 .
I wanted to delete this issue, but I did not know how, so I closed it.
Thank you so much :)

**Comment by bermarte** [comment]
Ok, it's better to delete this one and leave only one.
